- name: Pre-Install | Set default facts
  set_fact:
    use_firewalld: false
    configure_consul: false

- name: Pre-Install | Check running services
  service_facts:

- name: Pre-Install | Check Consul configuration
  when:
  - bsd_iscsi_target_config_consul | lower == 'true'
  - not (ansible_facts.services | map('quote') | join(',') | regex_search('consul'))
  fail: msg="Consul service not found - Cannot configure it"

- name: Pre-Install | Get Consul facts
  when:
  - bsd_iscsi_target_config_consul | lower == 'true'
  - ansible_facts.services | map('quote') | join(',') | regex_search('consul')
  set_fact:
    configure_consul: true
